### ISSUE TITLE
역할에 속한 사람 리스트 출력하기

### ISSUE THREAD

**Issue by WraithKim** [team-play-together/together-bot#13]
input: role list <role-name>
output: 이름1, 이름2, 이름3, 이름4...etc

**Comment by WraithKim** [comment]
이 기능을 구현하는데 있어서 생각보다 더 조사가 필요함.
role에서 members라는 속한 멤버 목록을 불러올 수 있는 필드가 있는데 이걸 받을려면 discord.py 1.5부터 추가된 intent라는 개념이 필요한 거 같음. - [관련 내용](https://github.com/Rapptz/discord.py/issues/5867)

위 내용을 이해하지 않고 구현하면 role.members가 역할에 속한 인원과 상관없이 길이가 0인 리스트를 반환함.

**Comment by lyuha** [comment]
DONE #15
