### ISSUE TITLE
MultiDict가 설치되지 않음.

### ISSUE THREAD

**Issue by WraithKim** [team-play-together/together-bot#14]
[https://stackoverflow.com/q/64250866](https://stackoverflow.com/q/64250866)
discord.py의 의존 패키지인거 같은데, python 3.9.0이 지원되지 않음. 해결하기 위해 3.8.6으로 낮춤.

**Comment by WraithKim** [comment]
bot-dev 채널에서 의논됨.
C++ 컴파일러 이슈와 관련 있어서 직접 빌드하면 되는 거였나 하여간 해결방안이 있긴 한데, 원래는 안 되는걸 억지로 해결하는 거라 그냥 되는 파이썬 버전으로 내리는 게 편함.

**Comment by lyuha** [comment]
python 버전을 올린다면, <https://pypi.org/project/discord.py/> 의  Programming Language 부분을 한번쯤은 확인해볼 것.
