### ISSUE TITLE
접두어 추가

### ISSUE THREAD

**Issue by WraithKim** [team-play-together/together-bot#16]
`@together-bot command subcommand arguments`는 너무 김.
`!command subcommand arguments` 처럼 맨션 대신 접두어를 보고 봇 명령을 인식하는 기능도 필요하다고 생각함.

**Comment by lyuha** [comment]
이미 ! 로 명령어 호출이 구현되어 있음

참고 : https://github.com/team-play-together/together-bot/blob/4a1cb528f23a54944e978112b856fa12f27bfd4e/together_bot/bot.py#L27
