### ISSUE TITLE
role get이 공백이 있는 역할 이름을 인식하지 못함

### ISSUE THREAD

**Issue by WraithKim** [team-play-together/together-bot#17]
`role get <rolename> <timeout>`으로 되어있는데, 역할 이름에 공백이 있을 경우, 
역할 이름의 두번째 음절을 timeout으로 인식함.

**Comment by WraithKim** [comment]
수정할 경우, role get의 help 텍스트도 수정 좀...

**Comment by WraithKim** [comment]
wraithkim(김동환)어제 오후 12:54

> 아무튼
> role create는 공백을 허용하는데
> role get은 두번째 인자가 타임아웃이라서
> 공백이 있는 역할을 인식 못하넴
> issue

lyuha어제 오후 12:59

> 아 공백있는 역할이 되긴 하는구나
> !role get "rolename with whitespace"
> 이건 안 되네 흠
> role create 단에서 막는 것이 더 가능성이 있어보이는데
> 잘 모르겠군

wraithkim(김동환)어제 오후 1:04

> bot developer는 공백이 있는 역할이라 난 role get의 duration 인자를 없애는게 좋다고... 생각
> play together 채널에 보면... ㅇㅇ
> 사람들이 공백 없는 역할만 만들것 같지 않음...(신텍스 에러 검사하기 귀찮)

**Comment by lyuha** [comment]
`async def get(self, ctx, name: str, duration: Optional[str]):` 라서 `role get "rolename with whitespace"` 으로 공백이 들어간 역할 호출 가능

함수 정의 참고 : https://github.com/team-play-together/together-bot/blob/777ab594d8aa01d8b7a3a37c214e665942508bb8/together_bot/role.py#L52
