### ISSUE TITLE
로깅 추가

### ISSUE THREAD

**Issue by WraithKim** [team-play-together/together-bot#5]
stderr에 대해서 하이라이트가 되지 않는 터미널 환경에선 오류 로그를 구분하기 어려움.
따라서 logging을 써서 각 로그 메세지마다 접두어를 붙여주는게 나을 듯.
ex)
[Error] This is error message blah blah
[Info] This is infomation blah blah

**Comment by lyuha** [comment]
#10 resolve this issue.
