### ISSUE TITLE
Time 명령어 테스트 추가

### ISSUE THREAD

**Issue by lyuha** [team-play-together/together-bot#63]
> time 명령어의 test 추가 #61 

위에 test 추가에 따라서 성공 외에 실패에 관한 테스트도 추가해야 한다.

- 경계 값 작성
- python int 가 가지는 범위에서 음수나 경계값에 대한 테스트 https://github.com/team-play-together/together-bot/blob/446ed94ef688e53dbf114a6746f11a09e6830877/together_bot/time.py#L56
- Datetime에서 KST 1-1-1 08:00 에서 UTC로 변경하면 어떻게 되는가?

**Comment by WraithKim** [comment]
### stale을 막기 위한 주저리주저리
`datetime.fromtimestamp()`에서 발생할 수 있는 예외 처리 필요 (`OSError`, `OverflowError`, `ValueError`)
 * timestamp 표현은 C의 `localtime()`함수에 의해 1970년~2038년으로 제한됨.
 * datetime의 표현 범위는 0001/01/01 00:00 ~ 9999/12/31 23:59
 * timedelta 범위는 고려해야 되나?

직접적인 time 명령어 테스트는 discord.py의 pytest 미지원으로 인해 할 수 없음.
경계값 예외를 처리하는 건 `time convert` 명령어에서 오류 메세지를 보내야 되기 때문에 `Time.convert()`내에서 직접 처리함.
어차피 예외 처리를 구현했는지 확인하기 위해 테스트를 추가하는거면 지금은 테스트 못하는 거 아닌가?

**Comment by WraithKim** [comment]
경계값 테스트는 위에서 말한 거처럼 discord.py가 안되면 개발자에게 강제할 수 없음. 테스트만 작성해두고, 나중에 테스트에 이런 Exception을 고려해야 된다는 걸 알려주는 용도로 밖에 못 씀. 일단 그렇게 추가는 해둠.

`datetime.fromtimestamp()`는 C 언어 함수를 사용하기 때문에 platform dependent 함. 따라서 OS마다 될 수도 있고 안 될 수도 있음. 여기부턴 정확한 이유를 찾아보기 어려워서 그만함. 그래서 테스트 목록도 아래 링크에서 raise 되는 것만 떼서 가져옴.  
https://bugs.python.org/issue13847
https://stackoverflow.com/q/37494983

**Comment by WraithKim** [comment]
Time 테스트에 대해서 더 추가할 게 생각 안나는데 닫아도 무방하지 않을까?
